# Generated by Django 5.2.6 on 2025-09-13 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='CarroSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('preco', models.CharField(max_length=20)),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='carros.garagem')),
            ],
        ),
    ]
